---
include:
  - keyboard: Kyria rev3
    shield: kyria_rev3_left nice_view_adapter nice_view
    board: nice_nano_v2
    artifact-name: zmk-kyria-rev3-left
  - keyboard: Kyria rev3
    shield: kyria_rev3_right nice_view_adapter nice_view
    board: nice_nano_v2
    artifact-name: zmk-kyria-rev3-right
  - keyboard: Auora Corne rev1
    shield: splitkb_aurora_corne_left nice_view_adapter nice_view
    board: nice_nano_v2
    artifact-name: zmk-aurora-corne-rev1-left
  - keyboard: Auora Corne rev1
    shield: splitkb_aurora_corne_right nice_view_adapter nice_view
    board: nice_nano_v2
    artifact-name: zmk-aurora-corne-rev1-right
