---
include:
  - board: nice_nano_v2
    shield: splitkb_aurora_sofle_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: splitkb_aurora_sofle_right nice_view_adapter nice_view

  - board: nice_nano_v2
    shield: kyria_rev3_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: kyria_rev3_right nice_view_adapter nice_view

  - board: nice_nano_v2
    shield: splitkb_aurora_corne_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_right nice_view_adapter nice_view
