---
include:
  - keyboard: Kyria rev3 MX
    shield: kyria_rev3_left nice_view_adapter nice_view
    board: nice_nano_v2
    cmake-args: -DEXTRA_CONF_FILE=../../config/kyria_rev3_mx.conf
    artifact-name: zmk-kyria-rev3-mx-left
  - keyboard: Kyria rev3 MX
    shield: kyria_rev3_right nice_view_adapter nice_view
    board: nice_nano_v2
    cmake-args: -DEXTRA_CONF_FILE=../../config/kyria_rev3_mx.conf
    artifact-name: zmk-kyria-rev3-mx-right
  - keyboard: Kyria rev3 choc
    shield: kyria_rev3_left
    board: nice_nano_v2
    cmake-args: -DEXTRA_CONF_FILE=../../config/kyria_rev3_choc.conf
    artifact-name: zmk-kyria-rev3-choc-left
  - keyboard: Kyria rev3 choc
    shield: kyria_rev3_right
    board: nice_nano_v2
    cmake-args: -DEXTRA_CONF_FILE=../../config/kyria_rev3_choc.conf
    artifact-name: zmk-kyria-rev3-choc-right
