parse_config:
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$

  raw_binding_map:
    # Layers
    "&lt L_NAV ESC":
      tap: $$mdi:keyboard-esc$$
      hold: nav
    "&mo L_MEDIA":
      hold: media
    "&mo L_FN":
      hold: fn
    "&mo L_SYM":
      hold: sym
    "&mo L_NUM":
      hold: num

    # System
    "&ss_to_file":
      tap: $$mdi:monitor-screenshot$$ 
      shifted: $$mdi:floppy$$
    "&ss_to_clip":
      tap: $$mdi:monitor-screenshot$$ 
      shifted: $$mdi:clipboard$$

    # Hardware
    "&rgb_ug RGB_TOG":
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:led-on$$
      shifted: $$mdi:led-outline$$
      type: toggle
    "&rgb_ug RGB_EFF":
      tap: $$mdi:led-on$$
      shifted: $$mdi:page-previous-outline$$
      type:    sym_by_sym
    "&rgb_ug RGB_HUI":
      tap:     $$mdi:led-on$$
      shifted: $$mdi:palette$$
      type:    sym_by_sym
    "&rgb_ug RGB_SAI":
      tap:     $$mdi:led-on$$
      shifted: $$mdi:eyedropper$$
      type:    sym_by_sym
    "&rgb_ug RGB_BRI":
      tap:     $$mdi:led-on$$
      shifted: $$mdi:white-balance-sunny$$
      type:    sym_by_sym
    "&rgb_ug RGB_BRD":
      tap:     $$mdi:led-outline$$
      shifted: $$mdi:white-balance-sunny$$
      type:    sym_by_sym
    "&rgb_ug RGB_SPI":
      tap:     $$mdi:led-on$$
      shifted: $$mdi:speedometer$$
      type:    sym_by_sym
    "&ext_power EP_TOG": $$mdi:power$$
    "&bt BT_SEL 0":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 1
    "&bt BT_SEL 1":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 2
    "&bt BT_SEL 2":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 3
    "&bt BT_SEL 3":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 4
    "&bt BT_SEL 4":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: 5
    "&bootloader":
      tap: $$mdi:progress-download$$
    "&sys_reset":
      type: bootloader
      tap: $$mdi:backup-restore$$

  zmk_keycode_map:
    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LGUI: $$mdi:linux$$
    LS(LC(LALT)): $$mdi:triangle$$

    # Whitespace
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    SPACE: $$mdi:keyboard-space$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DEL: $$mdi:backspace-reverse-outline$$
    INS: Ins

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    PG_UP: $$mdi:transfer-up$$
    PG_DN: $$mdi:transfer-down$$
    HOME: Home
    END: End

    # System
    K_COPY: $$mdi:content-copy$$
    K_PASTE: $$mdi:content-paste$$
    K_CUT: $$mdi:content-cut$$
    K_UNDO: $$mdi:undo$$
    K_REDO: $$mdi:redo$$

    # Hardware
    BT_CLR: $$mdi:bluetooth-off$$

    # Media
    C_PREV: $$mdi:skip-previous$$
    C_STOP: $$mdi:stop$$
    C_PP: $$mdi:play-pause$$
    C_NEXT: $$mdi:skip-next$$

    # Symbols
    "LS(COMMA)": ";"
    "LS(DOT)": ":"
    COMMA: ","
    DOT: "."
    NUHS: "'"
    "LS(N2)": "\""
    NUBS: "<"
    "LS(NUBS)": ">"
    "LS(MINUS)": "?"
    "LS(N1)": "!"
    "LS(N7)": "/"
    "GRAVE": "|"
    "LS(N8)": "("
    "LS(N9)": ")"
    "RA(N7)": "{"
    "RA(N0)": "}"
    "RA(N8)": "["
    "RA(N9)": "]"
    "SLASH": "-"
    "LS(N0)": "="
    "LS(NUHS)": "*"
    "LS(N5)": "%"
    "MINUS": "+"
    "LS(EQUAL)": "`"
    "EQUAL": "\\"
    "LS(N3)": "#"
    "LS(RBRC)": "^"
    "LS(N6)": "&"
    "RA(N4)": "$"
    "RA(RBRC)": "~"
    "RA(N2)": "@"
    "LS(SLASH)": "_"
    "LS(GRAVE)": "§"
    "RA(N3)": "£"
    "RA(N5)": "€"
    "SEMI": "Ø"
    "SQT": "Æ"
    "LBKT": "Å"

draw_config:
  # key dimensions, non-ortho layouts use key_h for width as well
  # key_w: 100 # This doesn't seem to do anything? 🤔
  key_h: 80

  # keys border radius
  key_rx: 4
  key_ry: 4

  # key labels line spacing for multi-line labels
  line_spacing: 1

  # combo box dimensions
  combo_w: 30
  combo_h: 30

  # padding from the edge of cap to top and bottom legends
  small_pad: 4

  # Padding between keys
  inner_pad_w: 1.5
  inner_pad_h: 1.5

  # padding between layers
  outer_pad_w: 0
  outer_pad_h: 0

  # gap between two halves for ortho layout generator
  # split_gap: 20 # This doesn't seem to have any effect either? 🤔

  # as it reads on the tin can, this comment is here for consistency
  append_colon_to_layer_header: false

  # shrink font size for legends wider than this many chars, set to 0 to disable
  # ideal value depends on the font size defined in svg_style and width of the boxes
  shrink_wide_legends: 5

  # Glyphs dimensions
  glyph_tap_size: 22
  glyph_hold_size: 16
  glyph_shifted_size: 16

  # Custom CSS
  svg_style: |
    /* inherit to force styles through use tags */
    svg path {
        fill: inherit;
    }

    /* font and background color specifications */
    svg.keymap {
        /*
         * ====================
         * Theme Variables
         * ====================
         */

        --logo-path: none;
        --logo-size: 12%;
        --logo-position: 49.5% 5%;

        /* === Colors === */

        --color--material--blue--50: rgb(227, 242, 253);
        --color--material--blue--100: rgb(187, 222, 251);
        --color--material--blue--200: rgb(144, 202, 249);
        --color--material--blue--300: rgb(100, 181, 246);
        --color--material--blue--400: rgb(66, 165, 245);
        --color--material--blue--500: rgb(33, 150, 243);
        --color--material--blue--600: rgb(30, 136, 229);
        --color--material--blue--700: rgb(25, 118, 210);
        --color--material--blue--800: rgb(21, 101, 192);
        --color--material--blue--900: rgb(13, 71, 161);
        --color--material--blue--a100: rgb(130, 177, 255);
        --color--material--blue--a200: rgb(68, 138, 255);
        --color--material--blue--a400: rgb(41, 121, 255);
        --color--material--blue--a700: rgb(41, 98, 255);

        --color--material--blue-gray--50: rgb(236, 239, 241);
        --color--material--blue-gray--100: rgb(207, 216, 220);
        --color--material--blue-gray--200: rgb(176, 190, 197);
        --color--material--blue-gray--300: rgb(144, 164, 174);
        --color--material--blue-gray--400: rgb(120, 144, 156);
        --color--material--blue-gray--500: rgb(96, 125, 139);
        --color--material--blue-gray--600: rgb(84, 110, 122);
        --color--material--blue-gray--700: rgb(69, 90, 100);
        --color--material--blue-gray--800: rgb(55, 71, 79);
        --color--material--blue-gray--900: rgb(38, 50, 56);

        --color--material--blue-light--50: rgb(225, 245, 254);
        --color--material--blue-light--100: rgb(179, 229, 252);
        --color--material--blue-light--200: rgb(129, 212, 250);
        --color--material--blue-light--300: rgb(79, 195, 247);
        --color--material--blue-light--400: rgb(41, 182, 246);
        --color--material--blue-light--500: rgb(3, 169, 244);
        --color--material--blue-light--600: rgb(3, 155, 229);
        --color--material--blue-light--700: rgb(2, 136, 209);
        --color--material--blue-light--800: rgb(2, 119, 189);
        --color--material--blue-light--900: rgb(1, 87, 155);
        --color--material--blue-light--a100: rgb(128, 216, 255);
        --color--material--blue-light--a200: rgb(64, 196, 255);
        --color--material--blue-light--a400: rgb(0, 176, 255);
        --color--material--blue-light--a700: rgb(0, 145, 234);

        --color--material--purple--50: rgb(243, 229, 245);
        --color--material--purple--100: rgb(225, 190, 231);
        --color--material--purple--200: rgb(206, 147, 216);
        --color--material--purple--300: rgb(186, 104, 200);
        --color--material--purple--400: rgb(171, 71, 188);
        --color--material--purple--500: rgb(156, 39, 176);
        --color--material--purple--600: rgb(142, 36, 170);
        --color--material--purple--700: rgb(123, 31, 162);
        --color--material--purple--800: rgb(106, 27, 154);
        --color--material--purple--900: rgb(74, 20, 140);
        --color--material--purple--a100: rgb(234, 128, 252);
        --color--material--purple--a200: rgb(224, 64, 251);
        --color--material--purple--a400: rgb(213, 0, 249);
        --color--material--purple--a700: rgb(170, 0, 255);

        --color--material--red--50: rgb(255, 235, 238);
        --color--material--red--100: rgb(255, 205, 210);
        --color--material--red--200: rgb(239, 154, 154);
        --color--material--red--300: rgb(229, 115, 115);
        --color--material--red--400: rgb(239, 83, 80);
        --color--material--red--500: rgb(244, 67, 54);
        --color--material--red--600: rgb(229, 57, 53);
        --color--material--red--700: rgb(211, 47, 47);
        --color--material--red--800: rgb(198, 40, 40);
        --color--material--red--900: rgb(183, 28, 28);
        --color--material--red--a100: rgb(255, 138, 128);
        --color--material--red--a200: rgb(255, 82, 82);
        --color--material--red--a400: rgb(255, 23, 68);
        --color--material--red--a700: rgb(213, 0, 0);

        --color--material--teal--50: rgb(224, 242, 241);
        --color--material--teal--100: rgb(178, 223, 219);
        --color--material--teal--200: rgb(128, 203, 196);
        --color--material--teal--300: rgb(77, 182, 172);
        --color--material--teal--400: rgb(38, 166, 154);
        --color--material--teal--500: rgb(0, 150, 136);
        --color--material--teal--600: rgb(0, 137, 123);
        --color--material--teal--700: rgb(0, 121, 107);
        --color--material--teal--800: rgb(0, 105, 92);
        --color--material--teal--900: rgb(0, 77, 64);
        --color--material--teal--a100: rgb(167, 255, 235);
        --color--material--teal--a200: rgb(100, 255, 218);
        --color--material--teal--a400: rgb(29, 233, 182);
        --color--material--teal--a700: rgb(0, 191, 165);

        --color--material--yellow--50: rgb(255, 253, 231);
        --color--material--yellow--100: rgb(255, 249, 196);
        --color--material--yellow--200: rgb(255, 245, 157);
        --color--material--yellow--300: rgb(255, 241, 118);
        --color--material--yellow--400: rgb(255, 238, 88);
        --color--material--yellow--500: rgb(255, 235, 59);
        --color--material--yellow--600: rgb(253, 216, 53);
        --color--material--yellow--700: rgb(251, 192, 45);
        --color--material--yellow--800: rgb(249, 168, 37);
        --color--material--yellow--900: rgb(245, 127, 23);
        --color--material--yellow--a100: rgb(255, 255, 141);
        --color--material--yellow--a200: rgb(255, 255, 0);
        --color--material--yellow--a400: rgb(255, 234, 0);
        --color--material--yellow--a700: rgb(255, 214, 0);

        --color--turquoise--500: rgb(51, 204, 204);

        --color--bg: transparent;
        --color--text: var(--color--material--blue-gray--900);

        --color--layer--text: var(--color--material--blue-gray--400);

        --color--key--bg: var(--color--material--blue-gray--50);
        --color--key--border: white;
        --color--key--text--tap: var(--color--text);
        --color--key--text--shifted: var(--color--material--blue-gray--400);
        --color--key--text--hold: var(--color--material--blue-gray--400);

        --color--combo--bg: var(--color--material--blue-gray--100);
        --color--combo--border: var(--color--combo--bg);
        --color--combo--dendron: var(--color--combo--border);
        --color--combo--text--tap: var(--color--material--blue-gray--800);
        --color--combo--text--shifted: var(--color--material--blue-gray--400);
        --color--combo--text--hold: var(--color--combo--text--tap);

        /*
         * ====================
         * /End Theme Variables
         * ====================
         */

        font-family: system-ui, sans-serif;
        font-size: 20px;
        font-weight: 600;
        font-kerning: normal;
        text-rendering: optimizeLegibility;
        fill: var(--color--text);
        background-color: var(--color--bg);
        background-image: var(--logo-path);
        background-repeat: no-repeat;
        background-position: var(--logo-position);
        background-size: var(--logo-size) auto;
    }

    rect,
    path {
      shape-rendering: geometricPrecision;
    }

    text {
        text-anchor: middle;
        dominant-baseline: middle;
        line-height: 1;
    }

    /* Layer labels */
    text.label {
        font-size: 36px;
        text-anchor: start;
        paint-order: stroke;
        fill: var(--color--layer--text);
        translate: 581px 146px;
    }

    /* Keys */
    rect.key,
    rect.combo {
        fill: var(--color--key--bg);
        stroke: var(--color--key--border);
    }
    .tap {
      fill: var(--color--key--text--tap);
    }
    .shifted,
    .hold {
        font-size: 16px;
        text-anchor: middle;
    }

    .shifted {
        dominant-baseline: hanging;
        fill: var(--color--key--text--shifted);
        translate: 26px 2px;
    }
    .shifted.glyph {
        translate: 26px 0px;
    }

    .hold {
        dominant-baseline: ideographic;
        fill: var(--color--key--text--hold);
        translate: 26px 4px;
    }
    .hold.glyph {
        translate: 26px 2px;
    }


    /*
     * Combos
     */
    .combo {
      --color--key--bg: var(--color--combo--bg);
      --color--key--border: var(--color--combo--border);
      --color--key--text--tap: var(--color--combo--text--tap);
      --color--key--text--shifted: var(--color--combo--text--shifted);
      --color--key--text--hold: var(--color--combo--text--hold);
    }
    rect.combo {
      opacity: 0.8;
      stroke-width: 0;
    }
    path.combo {
      stroke-width: 1;
      stroke: var(--color--combo--dendron);
      fill: none;
    }
    .combo.tap {
      font-size: 16px;
    }
    .combo.shifted {
      font-size: 13px;
      translate: -9px -2px;
    }
    .combo.shifted.glyph {
      translate: -9px -3px;
    }
    .combo.hold {
      font-size: 16px;
      translate: 0 0;
    }

    /*
     * Transparent, None, and Ghost Keys
     */
    .trans,
    .none,
    .ghost {
      opacity: 0.4;
    }

    /*
     * Overrides
     */
    /* Outer column + thumb keys */
    .keypos-0 .key,
    .keypos-11 .key,
    .keypos-12 .key,
    .keypos-23 .key,
    .keypos-24 .key,
    .keypos-30 .key,
    .keypos-31 .key,
    .keypos-32 .key,
    .keypos-33 .key,
    .keypos-39 .key,
    .keypos-40 .key,
    .keypos-41 .key,
    .keypos-42 .key,
    .keypos-43 .key,
    .keypos-44 .key,
    .keypos-45 .key,
    .keypos-46 .key,
    .keypos-47 .key,
    .keypos-48 .key,
    .keypos-49 .key {
        --color--key--bg: var(--color--material--blue-gray--100);
        --color--key--border: var(--color--material--blue-gray--50);
    }

    .keypos-11 .key {
        --color--key--bg: var(--color--material--red--300);
        --color--key--border: var(--color--material--red--200);
        --color--key--text--shifted: var(--color--key--text--tap);
        --color--key--text--hold: var(--color--key--text--tap);
    }

    .keypos-46 .key {
        --color--key--bg: var(--color--material--teal--200);
        --color--key--border: var(--color--material--teal--100);
    }
